# Site
name: 'New Mills Craft Market'
description: 'New Mills Craft Market'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 'newmillscraftmarket.github.io/'
disqus: ''
email: 'info@newmillscraftmarket.co.uk'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Lucy
      site:           https://www.newmillscraftmarket.co.uk
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Lucy, the author of New Mills Craft Market!"
      email:          lucy@newmillscraftmarket.co.uk
      twitter:        https://twitter.com/newmillscraftmarket
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]